# -*- coding: utf-8 -*-
"""Data preprocessing2_step2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XoSJKHNkzVmp7pT_hkAV2a1qtYhrSg_V
"""

#import libraries:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly as px
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
import statistics as sm
import statsmodels.api as stats
import math

#import excel cleaned data:
data = pd.read_csv("/content/IT Salary Survey EU  2020 - Clean and Pre processed_step1.csv")
data_bkp = data.copy()

#initial exploration:
#Viewing data
print("Data's head :\n ",data.head(2))
print("...............................................................................")
print("Data's Tail : \n", data.tail(3))
print("...............................................................................")
print("Data's Shape",data.shape)
print("...............................................................................")
print("Rows : ", data.shape[0])
print("...............................................................................")
print("Columns : ", data.shape[1])
print("...............................................................................")
print("Description :\n", data.describe())
print("...............................................................................")
print("Info :\n ",data.info())
print("...............................................................................")

#Renaming the columns:
data.rename(columns = {'Total years of experience':'Experience', 'Your main technology / programming language':'Main Technology', 'Other technologies/programming languages you use often':'Main_Tech_2','Yearly brutto salary (without bonus and stocks) in EUR':'Salary','Yearly bonus + stocks in EUR':'Bonus_Stocks_inclusion','Annual brutto salary (without bonus and stocks) one year ago. Only answer if staying in the same country':'Salary_1yr_ago','Annual bonus+stocks one year ago. Only answer if staying in same country':'Bonus_Stocks_1yr_ago','Number of vacation days':'Vacations','Main language at work':'Language','Have you lost your job due to the coronavirus outbreak?':'Job_lost_covid','Have you been forced to have a shorter working week (Kurzarbeit)? If yes, how many hours per week':'Shorter_working_week','Have you received additional monetary support from your employer due to Work From Home? If yes, how much in 2020 in EUR':'Additional income wfh' }, inplace = True)

data.columns

data.isnull().sum()

#Let us fill the columns which we know, which have yes or no..
data['Additional income wfh']
data['Additional income wfh'] = data['Additional income wfh'].fillna(0)

data['Additional income wfh']

data['Additional income wfh'].isnull().sum()

data['Shorter_working_week']
data['Shorter_working_week'] = data['Shorter_working_week'].fillna(0)

data['Shorter_working_week'].isnull().sum()

data['Job_lost_covid']
data.Job_lost_covid = data.Job_lost_covid.fillna('No')

data['Job_lost_covid'].isnull().sum()

data['Job_lost_covid'].value_counts()

data.dropna(subset=['Company type'], inplace=True)

data['Company type'].isnull().sum()

data.dropna(subset=['Company size'], inplace=True)

data['Company size'].isnull().sum()

data['Language'].value_counts()

#Imputing null values with most recurring value:
data.Language = data.Language.fillna('English')

data['Language'].value_counts()

data.isnull().sum()

data['Сontract duration'].value_counts()

data['Сontract duration'] = data['Сontract duration'].str.replace('0','Unlimited contract')
print(data)

data['Сontract duration'].value_counts()

data.isnull().sum()

data.info()

categorical = data.select_dtypes(include = 'object')

categorical.columns

data['Сontract duration'] = data['Сontract duration'].fillna('Unlimited contract')

data.isnull().sum()

data['Gender'].value_counts()

data['Gender'].isnull().sum()

data['Gender']=data.Gender.fillna("Male")

"""As rest of the data is critical data and we can't loose the data or impute it randomly, we will use excel analysis for the same."""

data.to_csv('IT_SALARY_Preprocessed2.csv', header=True, index=True)

"""Our data is clean now.. there are some features which have the value counts that needs to be removed with understandings, that we will do in excel."""